# Generated by Django 4.2.6 on 2023-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mid_name",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="middle name"),
        ),
    ]
